### ISSUE TITLE
Configuration migration: /var/lib/sbctl already exists!

### ISSUE THREAD

**Issue by joshlangley** [Foxboron/sbctl#337]
I'm not sure if this is a separate issue from #336 since there seems to be a similar problem with a different directory? That issue seems to also be about a permission denied problem though, so I'm putting this problem here.

I just updated my machine and Pacman started spamming the following during Post-transaction hooks:

```
old configuration detected. Please use `sbctl setup --migrate`
```
After it finished I ran the given command and got this error:
```
$USER in 🌐 $HOST in ~ as 󰒃
❯ sudo sbctl setup --migrate
[sudo] password for $USER: 
old configuration detected. Please use `sbctl setup --migrate`
/var/lib/sbctl already exists!
```
(Identifying info redacted.)

ptr1337 just also mentioned this here: https://github.com/Foxboron/sbctl/issues/336#issuecomment-2260564170

As with him, my `/var/lib/sbctl` was empty and removing it makes no difference. Running `sudo sbctl setup --migrate` puts it back empty.

**OS:** ArchLinux (fully updated)
**sbctl Version:** 0.15.1-1
**Kernel:** 6.10.2.hardened1-1

If there is any other relevant information I haven't included, please let me know and I'll add it.

Thank you for the hard work you've put into this utility! I really appreciate it!

**Comment by Foxboron** [comment]
Right, this was fixed in `0.15.2`. You can rerun this with `--disable-landlock` until I do a `0.15.3`.

**Comment by TheMemeSniper** [comment]
what should i do if the directory isn't empty? sorry if you already answered in another issue

**Comment by Foxboron** [comment]
@TheMemeSniper If the content of `/usr/share/secureboot` has been moved to `/var/lib/sbctl` you can rm the `/usr/share/secureboot` directory.

**Comment by joshlangley** [comment]
Wow! That was a fast update!

However, I am still getting the same problem, even with `--disable-landlock`:

```
$USER in 🌐 $HOST in ~ as 󰒃 
❯ pacman -Qs sbctl
local/sbctl 0.15.2-1
    Secure Boot key manager

$USER in 🌐 $HOST in ~ as 󰒃 
❯ sudo sbctl setup --migrate --disable-landlock 
old configuration detected. Please use `sbctl setup --migrate`
/var/lib/sbctl already exists!

$USER in 🌐 $HOST in ~ as 󰒃 
❯ sudo eza --long --all /var/lib/sbctl /usr/share/secureboot/
/var/lib/sbctl:

/usr/share/secureboot/:
.rw-r--r--   0 root 20 Jan 11:38 bundles.db
.rw-r--r-- 669 root 31 Jul 07:37 files.db
.rw-r--r--  36 root 16 Jan 11:46 GUID
drwxr-xr-x   - root 16 Jan 11:46 keys
```

**Comment by Foxboron** [comment]
rm the /var/lib/sbctl  directory and retry :)

**Comment by dkwo** [comment]
@Foxboron Would it be possible for sbctl to continue with migration, even in the case the directory /var/lib/sbctl exists but is empty, instead of aborting?
In Void linux we also have a hook that creates /var/lib/sbctl when the package is built, and it may be better to do it that way, similarly to systemd-tmpfiles/sysusers I guess.
Thanks for all the work btw.

**Comment by joshlangley** [comment]
Removing `/var/lib/sbctl` first worked! Thank you so much for your help!

Workaround summary for newcomers:
1. First upgrade to sbctl `0.15.2`.
1. Remove `/var/lib/sbctl` if it exists. (`sudo rmdir /var/lib/sbctl`)
1. Run migration *with* `--disable-landlock`. (`sudo sbctl setup --migrate --disable-landlock`)

**Comment by Foxboron** [comment]
> Would it be possible for sbctl to continue with migration, even in the case the directory /var/lib/sbctl exists but is empty, instead of aborting?

@dkwo 

It's intended to be a check to ensure we are not overwriting and already migrated installation. I can move this check to look for `/var/lib/sbctl/keys` instead?

**Comment by dkwo** [comment]
Thanks! Checking for the `keys` subdir should be good.

**Comment by Foxboron** [comment]
@dkwo  Fixed here https://github.com/Foxboron/sbctl/commit/de3aafc87395c18abb8d72d0a3cf6ebcb5312927
